// AUTH ACTION TYPES
export const GOOGLE_LOGIN_INIT = 'GOOGLE_LOGIN_INIT';
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_INIT';
export const GOOGLE_LOGIN_FAIL = 'GOOGLE_LOGIN_INIT';

export const USER_REGISTER_INIT = 'USER_REGISTER_INIT';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_INIT = 'USER_LOGIN_INIT';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const SIGNUP_SUCCESS_INIT = 'SIGNUP_SUCCESS_INIT';
export const SIGNUP_SUCCESS_SUCCESS = 'SIGNUP_SUCCESS_SUCCESS';
export const SIGNUP_SUCCESS_FAIL = 'SIGNUP_SUCCESS_FAIL';

export const FORGET_PASSWORD_INIT = 'FORGET_PASSWORD_INIT';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAIL = 'FORGET_PASSWORD_FAIL';

export const RESET_PASSWORD_INIT = 'RESET_PASSWORD_INIT';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const UPDATE_TIMEZONE_INIT = 'UPDATE_TIMEZONE_INIT';
export const UPDATE_TIMEZONE_SUCCESS = 'UPDATE_TIMEZONE_SUCCESS';
export const UPDATE_TIMEZONE_FAIL = 'UPDATE_TIMEZONE_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const UPDATE_USER_INIT = 'UPDATE_USER_INIT';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const DELETE_USER_INIT = 'DELETE_USER_INIT';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

// AGENCY ACTION TYPES
export const JOIN_TEAM_INIT = 'JOIN_TEAM_INIT';
export const JOIN_TEAM_SUCCESS = 'JOIN_TEAM_SUCCESS';
export const JOIN_TEAM_FAIL = 'JOIN_TEAM_FAIL';

export const All_AGENCY_INIT = 'All_AGENCY_INIT';
export const All_AGENCY_SUCCESS = 'All_AGENCY_SUCCESS';
export const All_AGENCY_FAIL = 'All_AGENCY_FAIL';

export const JOIN_AGENCY_INIT = 'JOIN_AGENCY_INIT';
export const JOIN_AGENCY_SUCCESS = 'JOIN_AGENCY_SUCCESS';
export const JOIN_AGENCY_FAIL = 'JOIN_AGENCY_FAIL';

export const SELECT_AGENCY_INIT = 'SELECT_AGENCY_INIT';
export const SELECT_AGENCY_SUCCESS = 'SELECT_AGENCY_SUCCESS';
export const SELECT_AGENCY_FAIL = 'SELECT_AGENCY_FAIL';

export const SEARCH_AGENCY_INIT = 'SEARCH_AGENCY_INIT';
export const SEARCH_AGENCY_SUCCESS = 'SEARCH_AGENCY_SUCCESS';
export const SEARCH_AGENCY_FAIL = 'SEARCH_AGENCY_FAIL';

export const AGENCY_STATUS_INIT = 'AGENCY_STATUS_INIT';
export const AGENCY_STATUS_SUCCESS = 'AGENCY_STATUS_SUCCESS';
export const AGENCY_STATUS_FAIL = 'AGENCY_STATUS_FAIL';

export const CREATE_AGENCY_INIT = 'CREATE_AGENCY_INIT';
export const CREATE_AGENCY_SUCCESS = 'CREATE_AGENCY_SUCCESS';
export const CREATE_AGENCY_FAIL = 'CREATE_AGENCY_FAIL';

export const AGENCY_USERS_INIT = 'AGENCY_USERS_INIT';
export const AGENCY_USERS_SUCCESS = 'AGENCY_USERS_SUCCESS';
export const AGENCY_USERS_FAIL = 'AGENCY_USERS_FAIL';

export const GET_USER_AGENCY_INIT = 'GET_USER_AGENCY_INIT';
export const GET_USER_AGENCY_SUCCESS = 'GET_USER_AGENCY_SUCCESS';
export const GET_USER_AGENCY_FAIL = 'GET_USER_AGENCY_FAIL';

export const GET_ALL_AGENCY_INIT = 'GET_ALL_AGENCY_INIT';
export const GET_ALL_AGENCY_SUCCESS = 'GET_ALL_AGENCY_SUCCESS';
export const GET_ALL_AGENCY_FAIL = 'GET_ALL_AGENCY_FAIL';

export const USER_PROFILE_INIT = 'USER_PROFILE_INIT';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const GET_INVITAIONS_INIT = 'GET_INVITAIONS_INIT';
export const GET_INVITAIONS_SUCCESS = 'GET_INVITAIONS_SUCCESS';
export const GET_INVITAIONS_FAIL = 'GET_INVITAIONS_FAIL';

export const SEND_INVITAIONS_INIT = 'SEND_INVITAIONS_INIT';
export const SEND_INVITAIONS_SUCCESS = 'SEND_INVITAIONS_SUCCESS';
export const SEND_INVITAIONS_FAIL = 'SEND_INVITAIONS_FAIL';

export const DELETE_INVITAIONS_INIT = 'DELETE_INVITAIONS_INIT';
export const DELETE_INVITAIONS_SUCCESS = 'DELETE_INVITAIONS_SUCCESS';
export const DELETE_INVITAIONS_FAIL = 'DELETE_INVITAIONS_FAIL';

export const ENABLE_AGENCY_USERS_INIT = 'ENABLE_AGENCY_USERS_INIT';
export const ENABLE_AGENCY_USERS_SUCCESS = 'ENABLE_AGENCY_USERS_SUCCESS';
export const ENABLE_AGENCY_USERS_FAIL = 'ENABLE_AGENCY_USERS_FAIL';

export const LEAVE_AGENCY_INIT = 'LEAVE_AGENCY_INIT';
export const LEAVE_AGENCY_SUCCESS = 'LEAVE_AGENCY_SUCCESS';
export const LEAVE_AGENCY_FAIL = 'LEAVE_AGENCY_FAIL';

export const LEAVE_PENDING_AGENCY_INIT = 'LEAVE_PENDING_AGENCY_INIT';
export const LEAVE_PENDING_AGENCY_SUCCESS = 'LEAVE_PENDING_AGENCY_SUCCESS';
export const LEAVE_PENDING_AGENCY_FAIL = 'LEAVE_PENDING_AGENCY_FAIL';

export const ENABLE_AGENCY_ROLE_INIT = 'ENABLE_AGENCY_ROLE_INIT';
export const ENABLE_AGENCY_ROLE_SUCCESS = 'ENABLE_AGENCY_ROLE_SUCCESS';
export const ENABLE_AGENCY_ROLE_FAIL = 'ENABLE_AGENCY_ROLE_FAIL';

export const DISABLE_AGENCY_ROLE_INIT = 'DISABLE_AGENCY_ROLE_INIT';
export const DISABLE_AGENCY_ROLE_SUCCESS = 'DISABLE_AGENCY_ROLE_SUCCESS';
export const DISABLE_AGENCY_ROLE_FAIL = 'DISABLE_AGENCY_ROLE_FAIL';

export const UPDATE_AGENCY_INFO_INIT = 'UPDATE_AGENCY_INFO_INIT';
export const UPDATE_AGENCY_INFO_SUCCESS = 'UPDATE_AGENCY_INFO_SUCCESS';
export const UPDATE_AGENCY_INFO_FAIL = 'UPDATE_AGENCY_INFO_FAIL';

export const GET_AGENCY_ROLES_INIT = 'GET_AGENCY_ROLES_INIT';
export const GET_AGENCY_ROLES_SUCCESS = 'GET_AGENCY_ROLES_SUCCESS';
export const GET_AGENCY_ROLES_FAIL = 'GET_AGENCY_ROLES_FAIL';

// JOBS ACTION TYPES
export const JOBS_INIT = 'JOBS_INIT';
export const JOBS_SUCCESS = 'JOBS_SUCCESS';
export const JOBS_FAIL = 'JOBS_FAIL';

export const HIGHLIGHT_JOBS_INIT = 'HIGHLIGHT_JOBS_INIT';
export const HIGHLIGHT_JOBS_SUCCESS = 'HIGHLIGHT_JOBS_SUCCESS';
export const HIGHLIGHT_JOBS_FAIL = 'HIGHLIGHT_JOBS_FAIL';

export const CREATE_ASSIGNMENT_INIT = 'CREATE_ASSIGNMENT_INIT';
export const CREATE_ASSIGNMENT_SUCCESS = 'CREATE_ASSIGNMENT_SUCCESS';
export const CREATE_ASSIGNMENT_FAIL = 'CREATE_ASSIGNMENT_FAIL';

export const JOBS_POSITIONS_INIT = 'JOBS_POSITIONS_INIT';
export const JOBS_POSITIONS_SUCCESS = 'JOBS_POSITIONS_SUCCESS';
export const JOBS_POSITIONS_FAIL = 'JOBS_POSITIONS_FAIL';

export const JOBS_WORKS_INIT = 'JOBS_WORKS_INIT';
export const JOBS_WORKS_SUCCESS = 'JOBS_WORKS_SUCCESS';
export const JOBS_WORKS_FAIL = 'JOBS_WORKS_FAIL';

export const JOBS_LIVINGS_INIT = 'JOBS_LIVINGS_INIT';
export const JOBS_LIVINGS_SUCCESS = 'JOBS_LIVINGS_SUCCESS';
export const JOBS_LIVINGS_FAIL = 'JOBS_LIVINGS_FAIL';

export const JOBS_STATUSES_INIT = 'JOBS_STATUSES_INIT';
export const JOBS_STATUSES_SUCCESS = 'JOBS_STATUSES_SUCCESS';
export const JOBS_STATUSES_FAIL = 'JOBS_STATUSES_FAIL';

export const JOBS_SKILLS_INIT = 'JOBS_SKILLS_INIT';
export const JOBS_SKILLS_SUCCESS = 'JOBS_SKILLS_SUCCESS';
export const JOBS_SKILLS_FAIL = 'JOBS_SKILLS_FAIL';

export const JOBS_FILTER_INIT = 'JOBS_FILTER_INIT';
export const JOBS_FILTER_SUCCESS = 'JOBS_FILTER_SUCCESS';
export const JOBS_FILTER_FAIL = 'JOBS_FILTER_FAIL';

export const JOB_INIT = 'JOB_INIT';
export const JOB_SUCCESS = 'JOB_SUCCESS';
export const JOB_FAIL = 'JOB_FAIL';

export const CREATE_JOB_INIT = 'CREATE_JOB_INIT';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL';

// CANDIDATE ACTION TYPES
export const CANDIDATE_ALL_INIT = 'CANDIDATE_ALL_INIT';
export const CANDIDATE_ALL_SUCCESS = 'CANDIDATE_ALL_SUCCESS';
export const CANDIDATE_ALL_FAIL = 'CANDIDATE_ALL_FAIL';

export const CANDIDATE_INIT = 'CANDIDATE_INIT';
export const CANDIDATE_SUCCESS = 'CANDIDATE_SUCCESS';
export const CANDIDATE_FAIL = 'CANDIDATE_FAIL';

export const GET_MESSAGE_INIT = 'GET_MESSAGE_INIT';
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';
export const GET_MESSAGE_FAIL = 'GET_MESSAGE_FAIL';

export const SEND_MESSAGE_INIT = 'SEND_MESSAGE_INIT';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

// ANALYTICS ACTION TYPES
export const METRICS_INIT = 'METRICS_INIT';
export const METRICS_SUCCESS = 'METRICS_SUCCESS';
export const METRICS_FAIL = 'METRICS_FAIL';

// EVENTS ACTION TYPE
export const CREATE_EVENT = 'CREATE_EVENT';
export const EVENTS_SUCCESS = 'EVENTS_SUCCESS';

export const TOP_AREA_CANDIDATE_INIT = 'TOP_AREA_CANDIDATE_INIT';
export const TOP_AREA_CANDIDATE_SUCCESS = 'TOP_AREA_CANDIDATE_SUCCESS';
export const TOP_AREA_CANDIDATE_FAIL = 'TOP_AREA_CANDIDATE_FAIL';

export const TOP_AREA_CLIENT_INIT = 'TOP_AREA_CLIENT_INIT';
export const TOP_AREA_CLIENT_SUCCESS = 'TOP_AREA_CLIENT_SUCCESS';
export const TOP_AREA_CLIENT_FAIL = 'TOP_AREA_CLIENT_FAIL';

export const TOP_AREA_COMPLETED_CLIENT_INIT = 'TOP_AREA_COMPLETED_CLIENT_INIT';
export const TOP_AREA_COMPLETED_CLIENT_SUCCESS =
  'TOP_AREA_COMPLETED_CLIENT_SUCCESS';
export const TOP_AREA_COMPLETED_CLIENT_FAIL = 'TOP_AREA_COMPLETED_CLIENT_FAIL';

export const TOP_SUBAREA_CANDIDATE_INIT = 'TOP_SUBAREA_CANDIDATE_INIT';
export const TOP_SUBAREA_CANDIDATE_SUCCESS = 'TOP_SUBAREA_CANDIDATE_SUCCESS';
export const TOP_SUBAREA_CANDIDATE_FAIL = 'TOP_SUBAREA_CANDIDATE_FAIL';

export const TOP_SUBAREA_CLIENT_INIT = 'TOP_SUBAREA_CLIENT_INIT';
export const TOP_SUBAREA_CLIENT_SUCCESS = 'TOP_SUBAREA_CLIENT_SUCCESS';
export const TOP_SUBAREA_CLIENT_FAIL = 'TOP_SUBAREA_CLIENT_FAIL';

export const TOP_PROFESSIONS_CLIENT_INIT = 'TOP_PROFESSIONS_CLIENT_INIT';
export const TOP_PROFESSIONS_CLIENT_SUCCESS = 'TOP_PROFESSIONS_CLIENT_SUCCESS';
export const TOP_PROFESSIONS_CLIENT_FAIL = 'TOP_PROFESSIONS_CLIENT_FAIL';

export const GENDER_CANDIDATE_INIT = 'GENDER_CANDIDATE_INIT';
export const GENDER_CANDIDATE_SUCCESS = 'GENDER_CANDIDATE_SUCCESS';
export const GENDER_CANDIDATE_FAIL = 'GENDER_CANDIDATE_FAIL';

export const COUNT_CANDIDATE_INIT = 'COUNT_CANDIDATE_INIT';
export const COUNT_CANDIDATE_SUCCESS = 'COUNT_CANDIDATE_SUCCESS';
export const COUNT_CANDIDATE_FAIL = 'COUNT_CANDIDATE_FAIL';

export const COUNT_JOBS_INIT = 'COUNT_JOBS_INIT';
export const COUNT_JOBS_SUCCESS = 'COUNT_JOBS_SUCCESS';
export const COUNT_JOBS_FAIL = 'COUNT_JOBS_FAIL';

// NANNIES ACTION TYPES
export const NANNIES_FORM_INIT = 'NANNIES_FORM_INIT';
export const NANNIES_FORM_SUCCESS = 'NANNIES_FORM_SUCCESS';
export const NANNIES_FORM_FAIL = 'NANNIES_FORM_FAIL';

export const NANNIESEDIT_FORM_INIT = 'NANNIESEDIT_FORM_INIT';
export const NANNIESEDIT_FORM_SUCCESS = 'NANNIESEDIT_FORM_SUCCESS';
export const NANNIESEDIT_FORM_FAIL = 'NANNIESEDIT_FORM_FAIL';

export const NANNIESPATCH_FORM_INIT = 'NANNIESPATCH_FORM_INIT';
export const NANNIESPATCH_FORM_SUCCESS = 'NANNIESPATCH_FORM_SUCCESS';
export const NANNIESPATCH_FORM_FAIL = 'NANNIESPATCH_FORM_FAIL';

export const GET_AVAILABILITIES_INIT = 'GET_AVAILABILITIES_INIT';
export const GET_AVAILABILITIES_SUCCESS = 'GET_AVAILABILITIES_SUCCESS';
export const GET_AVAILABILITIES_FAIL = 'GET_AVAILABILITIES_FAIL';

export const GET_LANGUAGES_INIT = 'GET_LANGUAGES_INIT';
export const GET_LANGUAGES_SUCCESS = 'GET_LANGUAGES_SUCCESS';
export const GET_LANGUAGES_FAIL = 'GET_LANGUAGES_FAIL';

export const GET_POSITIONS_INIT = 'GET_POSITIONS_INIT';
export const GET_POSITIONS_SUCCESS = 'GET_POSITIONS_SUCCESS';
export const GET_POSITIONS_FAIL = 'GET_POSITIONS_FAIL';

export const GET_WORKS_INIT = 'GET_WORKS_INIT';
export const GET_WORKS_SUCCESS = 'GET_WORKS_SUCCESS';
export const GET_WORKS_FAIL = 'GET_WORKS_FAIL';

export const GET_LIVINGS_INIT = 'GET_LIVINGS_INIT';
export const GET_LIVINGS_SUCCESS = 'GET_LIVINGS_SUCCESS';
export const GET_LIVINGS_FAIL = 'GET_LIVINGS_FAIL';

export const GET_STATUSES_INIT = 'GET_STATUSES_INIT';
export const GET_STATUSES_SUCCESS = 'GET_STATUSES_SUCCESS';
export const GET_STATUSES_FAIL = 'GET_STATUSES_FAIL';

export const GET_QSKILLS_INIT = 'GET_QSKILLS_INIT';
export const GET_QSKILLS_SUCCESS = 'GET_QSKILLS_SUCCESS';
export const GET_QSKILLS_FAIL = 'GET_QSKILLS_FAIL';

export const GET_SKILLS_INIT = 'GET_SKILLS_INIT';
export const GET_SKILLS_SUCCESS = 'GET_SKILLS_SUCCESS';
export const GET_SKILLS_FAIL = 'GET_SKILLS_FAIL';

export const GET_SINGLENANNY_INIT = 'GET_SINGLENANNY_INIT';
export const GET_SINGLENANNY_SUCCESS = 'GET_SINGLENANNY_SUCCESS';
export const GET_SINGLENANNY_FAIL = 'GET_SINGLENANNY_FAIL';

export const BLACKLIST_INIT = 'BLACKLIST_INIT';
export const BLACKLIST_SUCCESS = 'BLACKLIST_SUCCESS';
export const BLACKLIST_FAIL = 'BLACKLIST_FAIL';

export const GET_RATINGS_INIT = 'GET_RATINGS_INIT';
export const GET_RATINGS_SUCCESS = 'GET_RATINGS_SUCCESS';
export const GET_RATINGS_FAIL = 'GET_RATINGS_FAIL';

export const SELECT_RATINGS_INIT = 'SELECT_RATINGS_INIT';
export const SELECT_RATINGS_SUCCESS = 'SELECT_RATINGS_SUCCESS';
export const SELECT_RATINGS_FAIL = 'SELECT_RATINGS_FAIL';

export const SET_FILTER_INIT = 'SET_FILTER_INIT';
export const SET_FILTER_SUCCESS = 'SET_FILTER_SUCCESS';
export const SET_FILTER_FAIL = 'SET_FILTER_FAIL';

export const DELETE_NANNIES_INIT = 'DELETE_NANNIES_INIT';
export const DELETE_NANNIES_SUCCESS = 'DELETE_NANNIES_SUCCESS';
export const DELETE_NANNIES_FAIL = 'DELETE_NANNIES_FAIL';

export const DELETE_ALLNANNIES_INIT = 'DELETE_ALLNANNIES_INIT';
export const DELETE_ALLNANNIES_SUCCESS = 'DELETE_ALLNANNIES_SUCCESS';
export const DELETE_ALLNANNIES_FAIL = 'DELETE_ALLNANNIES_FAIL';

export const HIGHLIGHT_NANNIES_INIT = 'HIGHLIGHT_NANNIES_INIT';
export const HIGHLIGHT_NANNIES_SUCCESS = 'HIGHLIGHT_NANNIES_SUCCESS';
export const HIGHLIGHT_NANNIES_FAIL = 'HIGHLIGHT_NANNIES_FAIL';

// DASHBOARD ACTION TYPES
export const MONTHLY_STATS_INIT = 'MONTHLY_STATS_INIT';
export const MONTHLY_STATS_SUCCESS = 'MONTHLY_STATS_SUCCESS';
export const MONTHLY_STATS_FAIL = 'MONTHLY_STATS_FAIL';

export const CREATE_CATEGORY_INIT = 'CREATE_CATEGORY_INIT';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAIL = 'CREATE_CATEGORY_FAIL';

export const GET_CATEGORY_INIT = 'GET_CATEGORY_INIT';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';

export const DELETE_CATEGORY_INIT = 'DELETE_CATEGORY_INIT';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const UPDATE_CATEGORY_INIT = 'UPDATE_CATEGORY_INIT';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';

export const ADD_JOBS_INIT = 'ADD_JOBS_INIT';
export const ADD_JOBS_SUCCESS = 'ADD_JOBS_SUCCESS';
export const ADD_JOBS_FAIL = 'ADD_JOBS_FAIL';

export const CATEGORY_POSITION_INIT = 'CATEGORY_POSITION_INIT';
export const CATEGORY_POSITION_SUCCESS = 'CATEGORY_POSITION_SUCCESS';
export const CATEGORY_POSITION_FAIL = 'CATEGORY_POSITION_FAIL';

export const HIGHLIGHTED_NANNIES_INIT = 'HIGHLIGHTED_NANNIES_INIT';
export const HIGHLIGHTED_NANNIES_SUCCESS = 'HIGHLIGHTED_NANNIES_SUCCESS';
export const HIGHLIGHTED_NANNIES_FAIL = 'HIGHLIGHTED_NANNIES_FAIL';

export const JOBS_ACTIVITIES_INIT = 'JOBS_ACTIVITIES_INIT';
export const JOBS_ACTIVITIES_SUCCESS = 'JOBS_ACTIVITIES_SUCCESS';
export const JOBS_ACTIVITIES_FAIL = 'JOBS_ACTIVITIES_FAIL';

export const GET_COMMENTS_INIT = 'GET_COMMENTS_INIT';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';

export const CREATE_COMMENTS_INIT = 'CREATE_COMMENTS_INIT';
export const CREATE_COMMENTS_SUCCESS = 'CREATE_COMMENTS_SUCCESS';
export const CREATE_COMMENTS_FAIL = 'CREATE_COMMENTS_FAIL';

export const UPDATE_COMMENTS_INIT = 'UPDATE_COMMENTS_INIT';
export const UPDATE_COMMENTS_SUCCESS = 'UPDATE_COMMENTS_SUCCESS';
export const UPDATE_COMMENTS_FAIL = 'UPDATE_COMMENTS_FAIL';

export const DELETE_COMMENTS_INIT = 'DELETE_COMMENTS_INIT';
export const DELETE_COMMENTS_SUCCESS = 'DELETE_COMMENTS_SUCCESS';
export const DELETE_COMMENTS_FAIL = 'DELETE_COMMENTS_FAIL';

export const DELETE_JOBS_INIT = 'DELETE_JOBS_INIT';
export const DELETE_JOBS_SUCCESS = 'DELETE_JOBS_SUCCESS';
export const DELETE_JOBS_FAIL = 'DELETE_JOBS_FAIL';

export const MATCHES_INIT = 'MATCHES_INIT';
export const MATCHES_SUCCESS = 'MATCHES_SUCCESS';
export const MATCHES_FAIL = 'MATCHES_FAIL';

export const UPDATE_STATUS_INIT = 'UPDATE_STATUS_INIT';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAIL = 'UPDATE_STATUS_FAIL';

export const UPDATE_COVER_INIT = 'UPDATE_COVER_INIT';
export const UPDATE_COVER_SUCCESS = 'UPDATE_COVER_SUCCESS';
export const UPDATE_COVER_FAIL = 'UPDATE_COVER_FAIL';

export const UPDATE_JOB_INIT = 'UPDATE_JOB_INIT';
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS';
export const UPDATE_JOB_FAIL = 'UPDATE_JOB_FAIL';

export const DELETE_ASSIGNMENT_INIT = 'DELETE_ASSIGNMENT_INIT';
export const DELETE_ASSIGNMENT_SUCCESS = 'DELETE_ASSIGNMENT_SUCCESS';
export const DELETE_ASSIGNMENT_FAIL = 'DELETE_ASSIGNMENT_FAIL';

export const GET_JOBS_RATINGS_INIT = 'GET_JOBS_RATINGS_INIT';
export const GET_JOBS_RATINGS_SUCCESS = 'GET_JOBS_RATINGS_SUCCESS';
export const GET_JOBS_RATINGS_FAIL = 'GET_JOBS_RATINGS_FAIL';

export const UPDATE_JOB_RATING_INIT = 'UPDATE_JOB_RATING_INIT';
export const UPDATE_JOB_RATING_SUCCESS = 'UPDATE_JOB_RATING_SUCCESS';
export const UPDATE_JOB_RATING_FAIL = 'UPDATE_JOB_RATING_FAIL';

export const ADD_ASSIGNEE_INIT = 'ADD_ASSIGNEE_INIT';
export const ADD_ASSIGNEE_SUCCESS = 'ADD_ASSIGNEE_SUCCESS';
export const ADD_ASSIGNEE_FAIL = 'ADD_ASSIGNEE_FAIL';

export const GET_ASSIGNEE_USER_INIT = 'GET_ASSIGNEE_USER_INIT';
export const GET_ASSIGNEE_USER_SUCCESS = 'GET_ASSIGNEE_USER_SUCCESS';
export const GET_ASSIGNEE_USER_FAIL = 'GET_ASSIGNEE_USER_FAIL';

export const DELETE_ASSIGNEE_USER_INIT = 'DELETE_ASSIGNEE_USER_INIT';
export const DELETE_ASSIGNEE_USER_SUCCESS = 'DELETE_ASSIGNEE_USER_SUCCESS';
export const DELETE_ASSIGNEE_USER_FAIL = 'DELETE_ASSIGNEE_USER_FAIL';

export const FILTER_HJOBS_INIT = 'FILTER_HJOBS_INIT';
export const FILTER_HJOBS_SUCCESS = 'FILTER_HJOBS_SUCCESS';
export const FILTER_HJOBS_FAIL = 'FILTER_HJOBS_FAIL';

export const REMOVE_JOB_INIT = 'REMOVE_JOB_INIT';
export const REMOVE_JOB_SUCCESS = 'REMOVE_JOB_SUCCESS';
export const REMOVE_JOB_FAIL = 'REMOVE_JOB_FAIL';

export const TOGGLE_MESSAGE_INIT = 'TOGGLE_MESSAGE_INIT';
export const TOGGLE_MESSAGE_SUCCESS = 'TOGGLE_MESSAGE_SUCCESS';
export const TOGGLE_MESSAGE_FAIL = 'TOGGLE_MESSAGE_FAIL';

export const CREATE_ATTACHMENT_INIT = 'CREATE_ATTACHMENT_INIT';
export const CREATE_ATTACHMENT_SUCCESS = 'CREATE_ATTACHMENT_SUCCESS';
export const CREATE_ATTACHMENT_FAIL = 'CREATE_ATTACHMENT_FAIL';

export const UPDATE_ATTACHMENT_INIT = 'UPDATE_ATTACHMENT_INIT';
export const UPDATE_ATTACHMENT_SUCCESS = 'UPDATE_ATTACHMENT_SUCCESS';
export const UPDATE_ATTACHMENT_FAIL = 'UPDATE_ATTACHMENT_FAIL';

export const GET_ATTACHMENT_INIT = 'GET_ATTACHMENT_INIT';
export const GET_ATTACHMENT_SUCCESS = 'GET_ATTACHMENT_SUCCESS';
export const GET_ATTACHMENT_FAIL = 'GET_ATTACHMENT_FAIL';

export const DELETE_ATTACHMENT_INIT = 'DELETE_ATTACHMENT_INIT';
export const DELETE_ATTACHMENT_SUCCESS = 'DELETE_ATTACHMENT_SUCCESS';
export const DELETE_ATTACHMENT_FAIL = 'DELETE_ATTACHMENT_FAIL';

export const SINGLE_ATTACHMENT_INIT = 'SINGLE_ATTACHMENT_INIT';
export const SINGLE_ATTACHMENT_SUCCESS = 'SINGLE_ATTACHMENT_SUCCESS';
export const SINGLE_ATTACHMENT_FAIL = 'SINGLE_ATTACHMENT_FAIL';

//CALENDER ACTION TYPES
export const GET_SCHEDULES_INIT = 'GET_SCHEDULES_INIT';
export const GET_SCHEDULES_SUCCESS = 'GET_SCHEDULES_SUCCESS';
export const GET_SCHEDULES_FAIL = 'GET_SCHEDULES_FAIL';

export const ADD_NOTES_INIT = 'ADD_NOTES_INIT';
export const ADD_NOTES_SUCCESS = 'ADD_NOTES_SUCCESS';
export const ADD_NOTES_FAIL = 'ADD_NOTES_FAIL';

export const DELETE_NOTES_INIT = 'DELETE_NOTES_INIT';
export const DELETE_NOTES_SUCCESS = 'DELETE_NOTES_SUCCESS';
export const DELETE_NOTES_FAIL = 'DELETE_NOTES_FAIL';

export const TOGGLE_NOTES_INIT = 'TOGGLE_NOTES_INIT';
export const TOGGLE_NOTES_SUCCESS = 'TOGGLE_NOTES_SUCCESS';
export const TOGGLE_NOTES_FAIL = 'TOGGLE_NOTES_FAIL';

export const UPDATE_NOTES_INIT = 'UPDATE_NOTES_INIT';
export const UPDATE_NOTES_SUCCESS = 'UPDATE_NOTES_SUCCESS';
export const UPDATE_NOTES_FAIL = 'UPDATE_NOTES_FAIL';

export const UPDATE_EVENTS_INIT = 'UPDATE_EVENTS_INIT';
export const UPDATE_EVENTS_SUCCESS = 'UPDATE_EVENTS_SUCCESS';
export const UPDATE_EVENTS_FAIL = 'UPDATE_EVENTS_FAIL';

export const DELETE_EVENTS_INIT = 'DELETE_EVENTS_INIT';
export const DELETE_EVENTS_SUCCESS = 'DELETE_EVENTS_SUCCESS';
export const DELETE_EVENTS_FAIL = 'DELETE_EVENTS_FAIL';

export const CHECK_STATUS_INIT = 'CHECK_STATUS_INIT';
export const CHECK_STATUS_SUCCESS = 'CHECK_STATUS_SUCCESS';
export const CHECK_STATUS_FAIL = 'CHECK_STATUS_FAIL';

export const UPDATE_CALENDLY_INIT = 'UPDATE_CALENDLY_INIT';
export const UPDATE_CALENDLY_SUCCESS = 'UPDATE_CALENDLY_SUCCESS';
export const UPDATE_CALENDLY_FAIL = 'UPDATE_CALENDLY_FAIL';

// FILES ACTION TYPES
export const FILES_UPLOAD_INIT = 'FILES_UPLOAD_INIT';
export const FILES_UPLOAD_SUCCESS = 'FILES_UPLOAD_SUCCESS';
export const FILES_UPLOAD_FAIL = 'FILES_UPLOAD_FAIL';

// NOTIFICATIONS ACTION TYPES
export const NOTIFICATIONS_INIT = 'NOTIFICATIONS_INIT';
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS';
export const NOTIFICATIONS_FAIL = 'NOTIFICATIONS_FAIL';

export const DELETE_NOTIFICATIONS_INIT = 'DELETE_NOTIFICATIONS_INIT';
export const DELETE_NOTIFICATIONS_SUCCESS = 'DELETE_NOTIFICATIONS_SUCCESS';
export const DELETE_NOTIFICATIONS_FAIL = 'DELETE_NOTIFICATIONS_FAIL';

export const MARK_NOTIFICATION_INIT = 'MARK_NOTIFICATION_INIT';
export const MARK_NOTIFICATION_SUCCESS = 'MARK_NOTIFICATION_SUCCESS';
export const MARK_NOTIFICATION_FAIL = 'MARK_NOTIFICATION_FAIL';

export const MARK_ALL_NOTIFICATION_INIT = 'MARK_ALL_NOTIFICATION_INIT';
export const MARK_ALL_NOTIFICATION_SUCCESS = 'MARK_ALL_NOTIFICATION_SUCCESS';
export const MARK_ALL_NOTIFICATION_FAIL = 'MARK_ALL_NOTIFICATION_FAIL';

export const SINGLE_NOTIFICATION_INIT = 'SINGLE_NOTIFICATION_INIT';
export const SINGLE_NOTIFICATION_SUCCESS = 'SINGLE_NOTIFICATION_SUCCESS';
export const SINGLE_NOTIFICATION_FAIL = 'SINGLE_NOTIFICATION_FAIL';

export const DELETE_ALL_NOTIFICATIONS_INIT = 'DELETE_ALL_NOTIFICATIONS_INIT';
export const DELETE_ALL_NOTIFICATIONS_SUCCESS =
  'DELETE_ALL_NOTIFICATIONS_SUCCESS';
export const DELETE_ALL_NOTIFICATIONS_FAIL = 'DELETE_ALL_NOTIFICATIONS_FAIL';
